### ISSUE TITLE
Please add these buttons/links

### ISSUE THREAD

**Issue by jerxjac** [Nerwyn/android-tv-card#104]
Can you please add icons/links shown below?

FilmPlus:
source: com.guideplus.co
![FilmPlus](https://github.com/Nerwyn/android-tv-card/assets/38360412/14604df1-068c-4eda-8951-5431fa7120ac)

npo start:
source: nl.uitzendinggemist
![nposvg](https://github.com/Nerwyn/android-tv-card/assets/38360412/961693a3-5ad1-4b3b-9d60-d969231524c5)

kijk:
source: com.talpa.kijk
![kijk](https://github.com/Nerwyn/android-tv-card/assets/38360412/3f8ee4b8-37c3-4b3b-9ced-ce683cbb7a09)

**Comment by Nerwyn** [comment]
Those sources look like the app IDs rather than the deep links. Are you sure they work with the `remote.turn_on` service?

I should probably add support for launching default apps using the app ID anyway. All deep links include `://` so it should be easy to use that to determine which service to call.

**Comment by Nerwyn** [comment]
It also looks like these were uploaded as images and not SVG paths. If I try opening them in a new tab or viewing them with browser web tools they say they're private user images and I can't use them.

**Comment by Nerwyn** [comment]
Scratch that it was a GitHub bug. They'll be in the next 3.9.0 beta.

**Comment by Nerwyn** [comment]
Added in [3.9.0](https://github.com/Nerwyn/android-tv-card/releases/tag/3.9.0).
