### ISSUE TITLE
Buttons disappear after selection platform "kodi"

### ISSUE THREAD

**Issue by Vladd1980** [Nerwyn/android-tv-card#154]
when setting up using this example:
type: custom:android-tv-card
remote_id: remote.google_chromecast
media_player_id: media_player.google_chromecast
title: Example 1
rows:
  - - power
  - - back
    - home
    - tv
    - netflix
  - - youtube
    - spotify
    - netflix
  - - touchpad
  - - slider
  - - channel_up
    - channel_down
    - info
  - - rewind
    - play
    - spotify
    - pause
    - fast_forward
    
I get the correct picture and the correct button placement
But as soon as I select the KODI platform, most of the buttons disappear somewhere
![image](https://github.com/user-attachments/assets/ea3dcd56-7c83-4d5f-8334-9911f01134d6)

Right now my configuration looks like this:
media_player_id: media_player.android
remote_id: remote.android_tv_192_168_200_5
title: Example 3
platform: Kodi
rows:
  - - power
    - youtube
    - spotify
  - - touchpad
    - slider
  - - back
    - home
custom_actions:
  - type: slider
    name: slider
    range:
      - 0
      - 1
    step: 0.01
    value_attribute: volume_level

the same thing happens with other examples. What am I doing wrong?
![image](https://github.com/user-attachments/assets/740414f0-8d74-4678-8654-7f75b461b2ee)

**Comment by Nerwyn** [comment]
The buttons disappear because they are not valid default keys or sources for Kodi (Kodi has no default sources). If you want them to exist you need to create custom sources.

You can see the default key and source lists per platform either in the layout tab of the editor, or in the source code. [Here](https://github.com/Nerwyn/android-tv-card/blob/main/src/models/maps/kodi/defaultKeys.ts) is Kodi's default key list.

**Comment by Vladd1980** [comment]
thanks for the detailed answer. I hope my knowledge is enough to figure this out
