### ISSUE TITLE
Add ability to choose haptic type

### ISSUE THREAD

**Issue by tedgravlin** [Nerwyn/android-tv-card#162]
First of all, I absolutely love this card and the custom features row add-on you made. I use both every single day, so thank you!

**Is your feature request related to a problem? Please describe.**
The current haptic type used for most actions has some strange results on my Pixel 7a. From looking at the code, it appears the 'default' (or at least most commonly used) haptic type is 'light'. This haptic type on my Pixel 7a results in a vibration that is not ideal, and doesn't feel like vibrations used in other apps.

**Describe the solution you'd like**
It would be nice if we could choose between the 'light, 'medium', and 'heavy' vibration types for haptics within the Universal Remote Card. This could even just be a YAML-only option so as not to clutter the interface.

Thanks!

**Comment by Nerwyn** [comment]
I've put some thought into this and read through how the logic for calling haptics works in this card and am going to have to decline implementing this. Different haptic types are called all over the place depending on the type of interaction, and making that user configurable would be a mess.

Part of the reason why haptics Home Assistant haptics don't feel as good on Android is because Home Assistant app haptics event handling is [designed for iOS](https://companion.home-assistant.io/docs/integrations/haptics/). Android is capable of much better haptics than the Home Assistant app provides, but someone on the app team would have to update the iOS to Android haptic/vibration mapping.

**Comment by tedgravlin** [comment]
That's totally understandable, thank you for the insight! I'll dig around in the Android app's code and see if I can suggest some improvements. 
Thanks!
