### ISSUE TITLE
FullyKiosk Webview "Custom element doenst exist"

### ISSUE THREAD

**Issue by radoprajitno** [Nerwyn/android-tv-card#49]
**Checklist:**

- [Y ] I updated to the latest version available
- [ Y] I cleared the cache of my browser

**Release with the issue:**
3.2.0 - 3.2.4

**Last working release (if known):**
3.0.5 works, 3.1.3 untested

**Browser and Operating System:**
LOS 20, Fully Kiosk on Webview 120.0.6099.144

Hi...
I'm having issue with on my Fully Kiosk Browser - Webview 120.0.6099.144.
It shows "Custom Element Doesn't exist"
All 3 of my devices showing the same thing. 
- Mi Pad 6 MIUI -  Fully Kiosk Browser - Webview 120.0.6099.144.
- Mi 6 LOS 20 - Fully Kiosk Browser - Webview 120.0.6099.144.
- T295 - Fully Kiosk Browser - Webview 120.0.6099.144.

However it works well on Chrome Browser, same devices.

**Comment by Shinigami777** [comment]
I have the same problem. 
Works on:
- Windows 11 - Edge
- Tab S9+ Android 14 Webview 120.0.6099.144
- Tab A8 Android 13 Webview 120.0.6099.144 both HA app and  Fully Kiosk Browser

"Custom element doenst exist" on:
- Pixel 6 Android 14 Webview 120.0.6099.144
- Nexus 5 Android 11 Webview 120.0.6099.144 both Ha app and  Fully Kiosk Browser

**Comment by radoprajitno** [comment]
> I have the same problem. Works on:
> 
> * Windows 11 - Edge
> * Tab S9+ Android 14 Webview 120.0.6099.144
> * Tab A8 Android 13 Webview 120.0.6099.144 both HA app and  Fully Kiosk Browser
> 
> "Custom element doenst exist" on:
> 
> * Pixel 6 Android 14 Webview 120.0.6099.144
> * Nexus 5 Android 11 Webview 120.0.6099.144 both Ha app and  Fully Kiosk Browser

If found my solutions....

on my configuration.yaml file:

at first::
    - url: /hacsfiles/android-tv-card/android-tv-card.js
      type: module

and it supposed to be:
    - url: /hacsfiles/android-tv-card/android-tv-card.min.js  (with .min)
      type: module

hope it works

**Comment by Shinigami777** [comment]
> > I have the same problem. Works on:
> > 
> > * Windows 11 - Edge
> > * Tab S9+ Android 14 Webview 120.0.6099.144
> > * Tab A8 Android 13 Webview 120.0.6099.144 both HA app and  Fully Kiosk Browser
> > 
> > "Custom element doenst exist" on:
> > 
> > * Pixel 6 Android 14 Webview 120.0.6099.144
> > * Nexus 5 Android 11 Webview 120.0.6099.144 both Ha app and  Fully Kiosk Browser
> 
> If found my solutions....
> 
> on my configuration.yaml file:
> 
> at first:: - url: /hacsfiles/android-tv-card/android-tv-card.js type: module
> 
> and it supposed to be: - url: /hacsfiles/android-tv-card/android-tv-card.min.js (with .min) type: module
> 
> hope it works

Thanks, but that's not it. I checked it, but mine was correct with .min.

**Comment by Nerwyn** [comment]
It's probably/definitely a caching issue, especially since it's working on some devices but not others and the same device in a different browser. I changed the file suffix to `min.js` to be more accurate as it's a minified compiled JavaScript file, but it's been causing unexpected consequences for some useres if HACS fails to update the resource URL or if their individual devices caches don't update properly and keep trying to look for the old file name despite the resource URL being updated.

Can you try uninstalling android-tv-card, clearing cache within Fully Kiosk on your non-functioning devices, then reinstalling it? I think some other users had similar issues despite clearing cache and the issue eventually went away on its own once their browser caches properly updated.

**Comment by Shinigami777** [comment]
The last Card update completely fixed the problem. And earlier cleaning the cache memory did not fix the problem.

**Comment by Nerwyn** [comment]
In that case is this good to close @radoprajitno ?
