### ISSUE TITLE
support for fire tv on the keyboard

### ISSUE THREAD

**Issue by armedad** [Nerwyn/android-tv-card#62]
the current keyboards don't work completely on fire tv.  keys like backspace, delete, etc  are handled differently than chromecast

i'd love to be able to override arbitrary keys.  this would allow me to even replace the handling of alpha numerics.  but alternatively alternate keyboard_mode like kodi (as you suggested in the community thread) would solve for these specific keys.

**Comment by Nerwyn** [comment]
Keyboards (seamless, textbox, and search) are programmed differently than regular buttons and wouldn't be remappable without a major rewrite. Adding new keyboard modes for different platforms makes more sense since there are a finite number of platforms and variations that need to be supported.

I opted to use the Android Remote API commands for backspace, delete, enter, arrow left, and arrow right since they're much more performant, but can create an alternate Fire TV keyboard mode which sends these commands via ADB. I'll work on this along with a couple of other feature requests for the next minor version and share a beta here when it's ready.

**Comment by Nerwyn** [comment]
Implemented in 3.4.0, which is still in alpha as I implemented other feature requests. Set `keyboard_mode` to `FIRE TV`, and then backspace, delete, enter, and arrow left and right will be sent using ADB instead of the remote API.

**Comment by Nerwyn** [comment]
@armedad still waiting for your feedback

**Comment by armedad** [comment]
i'm getting "failed to call service/send_command, must contain at least one of entity_id, device_id, area_id

i only get that error on backspace/enter (don't have arrows to test).  alpha numerics and other character keys work fine.

**Comment by Nerwyn** [comment]
I'm not getting that error in my testing. The entity ID for keyboard calls is being set [here](https://github.com/Nerwyn/android-tv-card/blob/3.4.0-beta.006/src/classes/remote-keyboard.ts#L58-L63) and is being done pretty much the same way as it's done for alphanumeric keys. Have you tried clearing cache? This sounds like it could be a caching issue.

**Comment by armedad** [comment]
yeah, i figured there wouldn't be a special separate code path, so it was a
little confusing.  i'll try clearing cache...  but i was pretty sure i
had.
i'm also happy to jump into the js debugger and trace the calls, however
i've never done that for a homeassistant add-on.  is there a simple way or
doc on how to install the uncompiled js?   i'm happy to do that and trace
at source level to verify

**Comment by Nerwyn** [comment]
I'd have to reconfigure my build pipeline to spit out a non-minified copy of the card JS file, and I'm not sure if I want to deal with that headache. Glad to hear that it works!

**Comment by armedad** [comment]
yeah, not worth that time.  esp since it was indeed just the caching
issue.
thanks so much for making these updates!

**Comment by Nerwyn** [comment]
Added in [3.4.0](https://github.com/Nerwyn/android-tv-card/releases/tag/3.4.0)
