### ISSUE TITLE
Volume slider android like swipe mode

### ISSUE THREAD

**Issue by queimadus** [Nerwyn/android-tv-card#97]
**Is your feature request related to a problem? Please describe.**
When using the volume slider, the volume first jumps to where we first touch the sliding bar, follows the finger 1-to-1 and when we release the touch, the volume will be set to the final place where the finger was.

**Describe the solution you'd like**
It would be nice if we could offer an alternative mode of the slider input (maybe opt-in via a config option if there are users that prefer the old behaviour), where it behaved more like the android sliders. It doesn't matter where you first touch the slider, the delta applied to the initial volume is according to the swiping distance from the initial position.

Here's a video example of the volume slider on my android:

https://github.com/Nerwyn/android-tv-card/assets/1107697/8148ac9d-fcbf-46d1-aa04-f25e15e6f96d

**Comment by Nerwyn** [comment]
That's not how my volume slider works on Android 15, and I don't think it's possible to implement this behavior without creating a completely different slider.

As it is now this volume slider is a heavily stylized HTML input range, and it's clickable area is the thumb at the tip of the "on" area. When you click or tap anywhere on the slider, it moves the thumb under your pointer because that is the behavior of input ranges. Any further dragging is the pointer moving the input range thumb.
